BiomeEvents:
  Biomes:
    Swamp:
      WhileIn:
        Commands:
          - 'msg @p You are currently in the swamp!'
        Sounds:
          - Chance: 20
            Sound: 'minecraft:block.end_portal_frame.spawn'
            Category: Ambient
            Volume: 0.1
            Pitch: 1.0
            IsFollowingPlayer: true
            Permission: ''
    Desert:
      WhileIn:
        Commands:
          - 'msg @p You are currently in the swamp!'
        Sounds:
          - Chance: 10
            Sound: 'minecraft:block.end_portal_frame.fill'
            Category: Ambient
            Volume: 0.1
            Pitch: 0.5
            IsFollowingPlayer: false
            Permission: ''
  Settings:
    PositionChecksInTicks: 20
    PapiBiomePlaceholder: '%player_biome%'