# ========
#
# Placeholders:
#
#    This plugin is capable of PlaceholderAPI (https://www.spigotmc.org/resources/placeholderapi.6245/) placeholders!
#    If you want to use PlaceholderAPI placeholders for biomes (certain world generators hook into PAPI for custom biomes),
#       you can set the placeholder of your choice in Settings.PapiBiomePlaceholder.
#    E.g.: '%player_biome%' will use the placeholder from the PAPI Extension "Player".
#    YOU NEED TO MAKE SURE THAT YOU HAVE THE CORRESPONDING EXTENSION INSTALLED IF NEEDED!
#
# ---
#
# Internal placeholder:
#    If you don't want to use PlaceholderAPI, you can use these placeholders instead!
#
#    Placeholders:
#       - %world%    => [String] The world of the player
#       - %biome%    => [String] The biome of the player
#       - %x%        => [String] The x coordinates of the player
#       - %y%        => [String] The y coordinates of the player
#       - %z%        => [String] The z coordinates of the player
#       - %player%   => [String] The players' name
#
# ========
EnvironmentAdditions:
  Biomes:
    # The name of the biome group (see biomes.yml).
    - BiomeGroup: Snowy
      # The event that should occur WHILE players are IN this specific biome group.
      WhileIn:
        # The conditions that must apply before any event for this biome group will be performed.
        Condition: WhileRainyAndDay
        # A list of particle objects (see commands.yml).
        Commands:
          - CommonResponse
          - SnowyResponse
        # A list of particle objects (see particles.yml).
        Particles:
          - Snow
        # A list of sound objects (see sounds.yml).
        Sounds:
          - PortalFrameSpawn
          - CrimsonAdditions

    - BiomeGroup: Swamp
      WhileIn:
        Commands:
          - SwampyResponse
        Sounds:
          - PortalFrameFill

  Settings:
    # The time in ticks in which the plugin should check the current biomes of all players
    # The HIGHER this integer is, the FEWER checks will be made => Better performance, poorer experience
    # The LOWER this integer is, the HIGHER checks will be made => Poorer performance, better experience
    PositionChecksInTicks: 20
    # Have a look at the Placeholder description section!
    # Leave it as it is or empty ('') to use for vanilla worlds.
    PapiBiomePlaceholder: '%player_biome%'
    # Whether a single group or all of them should be executed.
    # If set to true and multiple groups (e.g.: particles) have been configured, only one will randomly get picked.
    # If set to false and multiple groups (e.g.: particles) have been configured, all of them will get executed.
    UseSingleGroupMode: true