name: EnvironmentAdditions
main: net.lizardnetwork.environmentadditions.EnvironmentAdditions
version: 2.0.0
api-version: 1.19
author: xIRoXaSx
softdepend: [PlaceholderAPI]
commands:
  environment:
    description: Main command for EnvironmentAdditions
    usage: /<command>
    permission: environmentadditions.admin
    permission-message: ""
    aliases:
      - "envadd"
      - "envad"
      - "ea"